import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isDev = process.argv[2] === "dev";

function copyCss() {
	if (fs.existsSync("src/styles.css")) {
		fs.copyFileSync("src/styles.css", "styles.css");
	}
}

copyCss();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: isDev ? "inline" : false,
	treeShaking: true,
	outfile: "main.js",
	minify: !isDev,
	plugins: [
		{
			name: "copy-css",
			setup(build) {
				build.onEnd(() => {
					copyCss();
				});
			},
		},
	],
});

if (isDev) {
	await context.watch();
} else {
	await context.rebuild();
	process.exit(0);
}
